### PR TITLE
Migrate DWSIM food props batch1

### PR DESCRIPTION
**Pull request by sumitnegi7**
Sir @maneetgoyal  have rechecked the PR you can review it meanwhile i will recheck and update precision in other PR's.

### CODE REVIEW

**Comment by maneetgoyal** [comment]
@sumitnegi7 Made some corrections. Please verify.

Also, a bunch of values in Linoleic acid look incorrect.

**Comment by maneetgoyal** [comment]
Also, avoid reducing the precision of the number. Add as many decimal places as mentioned in the resources.

**Comment by sumitnegi7** [comment]
Okay sir will recheck the values and add the precision as given in the resource.

**Review by maneetgoyal — APPROVED** [review]
LGTM

**Pull request merged**
