### PR TITLE
Qur786/#9 migrate density data

### PR DESCRIPTION
**Pull request by qur786**
Migrated first batch of Density Data

### CODE REVIEW

**Comment by saikat-samanta** [comment]
Looks good 👍

**Comment by qur786** [comment]
> @qur786 Why is `Thermal conductivity data` been added to this PR?

I mistakenly added the remote branch of 'thermal conductivity' with my local density data . I will try to remove this pull request and do the new pull request for density data

**Comment by sumitnegi7** [comment]
@qur786  sync with master resolve merge conflicts and create a new PR.

**Comment by qur786** [comment]
So much conflict

**Pull request closed without merging**
